import React,{useEffect,useState} from 'react';
import {Badge,Button,Notice,Panel} from './components.jsx';
const modes=[['baseline','Baseline','Measure normal TLS requests.'],['failure','Stop a backend','Close one disposable server, observe failover, then restore it.'],['latency','Inject latency','Add 350 ms of delay against a 150 ms request deadline.'],['fairness','Tenant fairness','Compare a shared pool with a one-slot allowance per tenant.']];
export default function Lab({gateway:g}){
 const [state,setState]=useState(null),[error,setError]=useState(''),[pending,setPending]=useState(false),[selected,setSelected]=useState('');
 useEffect(()=>{let live=true,timer;const read=async()=>{try{const data=await g.readLab();if(live){setState(data);setError('');if(data.running)timer=setTimeout(read,50);}}catch(e){if(live)setError(e.message)}};read();return()=>{live=false;clearTimeout(timer)}},[g.token,pending]);
 async function start(mode){setPending(true);setError('');setSelected('');try{setState(await g.startLab(mode));}catch(e){setError(e.message)}finally{setPending(false)}}
 const trace=state?.requests?.find(r=>r.id===selected);
 function download(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`gateforge-${state.mode}-evidence.json`;a.click();URL.revokeObjectURL(url);}
 return <div className="space-y-6"><Notice>{error||state?.error}</Notice><p className="rounded-xl border border-teal-200 bg-teal-50 p-5 text-sm leading-6 text-teal-900">Real requests, isolated backends. Each experiment creates disposable loopback servers and synthetic tenants. It never changes your routes, keys, databases or production backends. One experiment runs per instance, with a 12-second ceiling.</p>
 <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{modes.map(([mode,name,description])=><section key={mode} className="panel flex flex-col gap-4 p-5"><h2 className="font-semibold">{name}</h2><p className="grow text-xs leading-6 text-slate-500">{description}</p><Button onClick={()=>start(mode)} disabled={pending||state?.running}>Run {name.toLowerCase()}</Button></section>)}</div>
 {state?.mode&&<><Panel title={`${state.mode} experiment`} subtitle={state.running?'Live measurements · refreshes every second':'Experiment complete'} action={<Badge tone={state.running?'accent':'success'}>{state.phase}</Badge>}><div className="grid gap-4 p-6 sm:grid-cols-4"><div><p className="text-xs text-slate-500">Elapsed</p><strong>{((state.duration_ms||0)/1000).toFixed(1)} s</strong></div><div><p className="text-xs text-slate-500">In-flight / bound</p><strong>{state.concurrency.active} / {state.concurrency.limit}</strong></div><div><p className="text-xs text-slate-500">Peak process heap</p><strong>{((state.heap_peak_bytes||0)/1048576).toFixed(1)} MiB</strong></div><div><p className="text-xs text-slate-500">Disposable backends</p>{state.backends?.map(b=><div key={b.name}><Badge tone={b.healthy?'success':'danger'}>{b.name}: {b.healthy?'healthy':'unavailable'}</Badge></div>)}</div></div></Panel>
 <Panel title="Measured outcomes" subtitle="Latency includes TLS, gateway handling and a complete response body. Errors include transport failures and 5xx; 429 rejections are separate."><div className="table-scroll"><table className="data-table"><thead><tr><th>Phase / tenant</th><th>Completed</th><th>Success</th><th>429</th><th>Errors</th><th>504</th><th>Retries</th><th>p50</th><th>p99</th><th>Req/s</th></tr></thead><tbody>{state.summary?.map(row=><tr key={row.phase+row.tenant}><td>{row.phase}<br/><Badge tone={row.tenant==='quiet'?'success':'warning'}>{row.tenant}</Badge></td><td>{row.requests}</td><td>{row.success}</td><td>{row.rejected}</td><td>{row.errors}</td><td>{row.timeouts}</td><td>{row.retries}</td><td>{row.p50_ms.toFixed(1)} ms</td><td>{row.p99_ms.toFixed(1)} ms</td><td>{row.rps.toFixed(1)}</td></tr>)}</tbody></table></div></Panel>
 <Panel title="Recorded decisions" subtitle="Representative real requests retained across experiment phases."><div className="flex flex-wrap gap-2 p-5">{state.requests?.map(r=><Button key={r.id} variant="secondary" onClick={()=>setSelected(r.id)}>{r.status} · {r.id.slice(0,6)}</Button>)}</div>{trace&&<ol className="space-y-3 border-t p-5">{trace.events.map((e,i)=><li key={i} className="rounded-xl bg-slate-950 p-4 text-slate-200"><div className="mb-2 text-xs text-teal-300">{i+1}. {e.stage} · {e.outcome} · +{e.elapsed_ms.toFixed(2)} ms</div><p className="text-sm">{e.reason}</p></li>)}</ol>}</Panel>
 <div className="flex flex-wrap items-center gap-4"><Button variant="secondary" onClick={download} disabled={state.running}>Download evidence JSON</Button><code className="text-xs text-slate-500">go run -buildvcs=true ./cmd/evidence -scenario all -repeat 3</code></div><p className="text-xs leading-6 text-slate-500">{state.go_version} · {state.os}/{state.arch} · {state.cpus} CPUs · GOMAXPROCS {state.gomaxprocs}. This is a bounded, closed-loop synthetic experiment, not a production capacity guarantee. Memory is process-wide Go heap (client, gateway, backends and dashboard workload), not isolated gateway RSS. The fairness comparison uses 12 busy workers and one quiet worker; requests wait 25 ms between completions. Production defaults are 128 in-flight requests per instance and 16 per authenticated tenant; the demo uses four and one to make contention visible.</p></>}
 </div>
}
