import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Badge, Button, Icon, Logo, Modal, Notice } from './components.jsx';
import { Keys, Overview, Routes, SecretModal } from './pages.jsx';
import { useGateway } from './useGateway.js';
import Learn from './Learn.jsx';
import SignIn from './SignIn.jsx';
import Audit from './Audit.jsx';
import Requests from './Requests.jsx';
import Lab from './Lab.jsx';
import './style.css';

const navigation = [{name:'Overview',icon:'overview'}, {name:'Requests',icon:'activity'}, {name:'Failure lab',icon:'server'}, {name:'Routes',icon:'routes'}, {name:'API keys',icon:'key'}, {name:'Audit log',icon:'shield'}];
const headings = { 'Failure lab': ['Failure lab & evidence', 'Explore real failures and fairness in an isolated environment.'],
  Requests: ['Explain this request', 'Follow the decisions behind real API traffic.'],
  Overview: ['Gateway overview', 'A clear view of your traffic, services, and performance.'],
  Routes: ['Route policies', 'Set access, quotas, and timeouts for your services.'],
  'Audit log': ['Administrator audit trail', 'Track who changed configuration and access.'],
  'API keys': ['Access management', 'Control who can call your APIs, one scoped key at a time.'],
};
function Login({ gateway: g }) {
  return <main className="login-grid"><section className="login-story"><Logo light/><div className="my-auto py-16 lg:py-20"><p className="mb-6 text-[10px] font-semibold tracking-[.23em] text-teal-300">API GATEWAY & DEVELOPER PLATFORM</p><h1 className="max-w-lg text-5xl leading-[1.12] font-semibold tracking-[-.045em] xl:text-6xl">Your APIs.<br/><span className="text-teal-300">Under control.</span></h1><p className="mt-6 max-w-sm text-sm leading-7 text-slate-400">One place to route traffic, protect your services, and see what’s happening across your gateway.</p><div className="architecture-card mt-12 max-w-md"><div className="flex items-center gap-2 border-b border-white/10 pb-4 text-[10px] tracking-widest text-slate-400"><span className="size-1.5 rounded-full bg-teal-300"/>GATEWAY ARCHITECTURE</div><div className="my-6 flex items-center gap-3 text-xs"><span className="rounded-lg border border-white/15 px-3 py-2 text-slate-300">Client</span><span className="h-px flex-1 bg-white/15"/><span className="flex items-center gap-2 rounded-lg border border-teal-300/30 bg-teal-300/10 px-4 py-3 text-teal-200"><Icon name="shield" className="size-4"/>GateForge</span><span className="h-px flex-1 bg-white/15"/><Icon name="server" className="text-slate-400"/></div><div className="flex flex-wrap gap-2">{['/users','/orders','/catalog'].map(path => <code key={path} className="rounded-md bg-white/5 px-3 py-1.5 text-[10px] text-slate-400">{path}</code>)}</div></div></div><div className="flex flex-wrap gap-5 text-[10px] text-slate-400"><span className="flex items-center gap-1.5"><Icon name="shield" className="size-3.5"/>Scoped access</span><span className="flex items-center gap-1.5"><Icon name="activity" className="size-3.5"/>Live metrics</span><span className="flex items-center gap-1.5"><Icon name="routes" className="size-3.5"/>Resilient routing</span></div></section>
    <section className="flex min-h-screen flex-col bg-[#f8fafb] px-6 py-8 sm:px-12 lg:px-16"><div className="flex justify-end"><a className="inline-flex items-center gap-2 text-xs font-medium text-slate-500 hover:text-teal-700" href="/catalog/items" target="_blank" rel="noreferrer">Explore the public API<Icon name="arrow" className="size-3.5"/></a></div><div className="mx-auto my-auto w-full max-w-[370px] py-16"><div className="mb-8 flex size-12 items-center justify-center rounded-2xl border border-slate-200 bg-white text-teal-700 shadow-sm"><Icon name="key"/></div><p className="mb-3 text-[10px] font-semibold tracking-[.18em] text-slate-400">ADMINISTRATOR ACCESS</p><h2 className="text-3xl font-semibold tracking-tight text-slate-900">Welcome to GateForge</h2><SignIn gateway={g}/><div className="mt-10 border-t border-slate-200 pt-6"><a href="#learn" className="group flex items-center justify-between rounded-xl border border-slate-200 bg-white p-4 hover:border-teal-300"><div className="flex items-center gap-3"><Icon name="book" className="text-teal-700"/><div><p className="text-xs font-semibold text-slate-700">New to API gateways?</p><p className="mt-1 text-[11px] text-slate-400">Explore the interactive walkthrough</p></div></div><Icon name="arrow" className="size-4 text-slate-400 group-hover:text-teal-700"/></a></div></div><p className="text-center text-[10px] text-slate-400">GateForge control plane · Authorized administrators only</p></section></main>;
}
function App() {
  const [learnOpen, setLearnOpen] = useState(() => window.location.hash === '#learn');
  const [mobileNav, setMobileNav] = useState(false);
  useEffect(() => { const update = () => setLearnOpen(window.location.hash === '#learn'); window.addEventListener('hashchange', update); return () => window.removeEventListener('hashchange', update); }, []);
  const g = useGateway(learnOpen);
  const openLearn = () => { setMobileNav(false); window.location.hash = 'learn'; };
  const select = name => { g.select(name); setMobileNav(false); };
  const nav = <nav aria-label="Main navigation" className="space-y-1.5">{navigation.map(item => <button key={item.name} className={`nav-link ${g.tab === item.name ? 'is-active' : ''}`} aria-current={g.tab === item.name ? 'page' : undefined} disabled={g.busy} onClick={() => select(item.name)}><Icon name={item.icon} className="size-[18px]"/>{item.name}{item.name === 'Routes' && <span className="ml-auto rounded bg-white/10 px-1.5 py-0.5 text-[10px]">{g.config?.routes.length || 0}</span>}</button>)}</nav>;
  if (learnOpen) return <Learn onClose={() => { window.location.hash = ''; }}/>;
  if (!g.token) return <Login gateway={g}/>;
  return <div className="min-h-screen bg-[#f6f8fa]"><a className="skip-link" href="#content">Skip to content</a><aside className="dashboard-sidebar"><Logo light/><div className="mt-10 rounded-xl border border-white/10 bg-white/[.035] p-3.5"><div className="flex items-center gap-2.5"><span className="rounded-md bg-white/10 p-1.5 text-slate-300"><Icon name="server" className="size-4"/></span><div><p className="text-xs font-medium text-slate-200">Gateway workspace</p><p className="mt-1 text-[10px] text-slate-500">Control plane</p></div></div></div><p className="mt-9 mb-4 px-3 text-[9px] font-semibold tracking-[.2em] text-slate-500">WORKSPACE</p>{nav}<div className="mt-8 border-t border-white/10 pt-6"><button className="nav-link" onClick={openLearn} disabled={g.busy}><Icon name="book" className="size-[18px]"/>How it works<Icon name="arrow" className="ml-auto size-3.5"/></button></div><div className="mt-auto pt-10"><div className="mb-5 flex items-center gap-2 px-3 text-[11px] text-slate-400"><span className={`size-1.5 rounded-full ${g.pollError ? 'bg-amber-400' : 'bg-teal-300'}`}/>{g.pollError ? 'Connection needs attention' : 'Gateway connected'}</div><button className="nav-link border border-white/10" onClick={g.signOut} disabled={g.busy}><Icon name="logout" className="size-4"/>Sign out</button></div></aside>
    <div className="lg:ml-[244px]"><header className="flex h-[72px] items-center justify-between gap-3 border-b border-slate-200 bg-white/85 px-5 backdrop-blur-sm sm:px-8"><div className="flex items-center gap-3"><button className="rounded-lg p-2 text-slate-600 lg:hidden" aria-label="Open navigation" onClick={() => setMobileNav(true)}><Icon name="menu"/></button><div className="text-xs text-slate-400"><span className="hidden sm:inline">Workspace <span className="mx-3 text-slate-300">/</span></span><span className="font-medium text-slate-700">{g.tab}</span></div></div><div className="flex items-center gap-4"><Badge tone={g.pollError ? 'warning' : 'success'} dot>{g.pollError ? 'Reconnecting' : 'Connected'}</Badge><div className="hidden items-center gap-2 border-l border-slate-200 pl-4 text-xs text-slate-500 sm:flex"><span className="rounded-full bg-slate-100 p-2"><Icon name="shield" className="size-4 text-slate-500"/></span><span className="max-w-48 truncate">{g.identity?.email || 'Administrator'}</span></div></div></header>
    <main id="content" className="mx-auto max-w-[1480px] px-5 py-8 sm:px-8 sm:py-10 xl:px-10"><div className="mb-8 flex flex-wrap items-start justify-between gap-5"><div><p className="mb-2 text-[9px] font-semibold tracking-[.2em] text-teal-700">GATEFORGE / CONTROL ROOM</p><h1 className="text-[28px] font-semibold leading-tight tracking-tight text-slate-900 sm:text-[30px]">{headings[g.tab][0]}</h1><p className="mt-2 text-sm leading-6 text-slate-500">{headings[g.tab][1]}</p></div><div className="flex items-center gap-3 sm:pt-3"><span className="hidden text-[10px] text-slate-400 xl:block">Updated {g.updated?.toLocaleTimeString()}</span><Button variant="secondary" icon="refresh" busy={g.busy} onClick={g.refresh}>Refresh</Button></div></div><div className="mb-6 space-y-3"><Notice onClose={() => g.setError('')}>{g.error}</Notice><Notice>{g.pollError ? `Live updates paused. ${g.pollError}` : ''}</Notice><Notice type="success" onClose={() => g.setNotice('')}>{g.notice}</Notice></div><div aria-busy={g.busy}>{g.tab === 'Overview' ? <Overview gateway={g}/> : g.tab === 'Failure lab' ? <Lab gateway={g}/> : g.tab === 'Requests' ? <Requests gateway={g}/> : g.tab === 'Routes' ? <Routes gateway={g}/> : g.tab === 'Audit log' ? <Audit gateway={g}/> : <Keys gateway={g}/>}</div><footer className="mt-10 flex flex-wrap items-center justify-between gap-2 border-t border-slate-200 pt-5 text-[10px] text-slate-400"><span>GateForge · API Gateway & Developer Platform</span><button className="hover:text-teal-700" onClick={openLearn}>Understand your gateway →</button></footer></main></div>
    <Modal open={mobileNav} title="Workspace" onClose={() => setMobileNav(false)}><div className="mobile-navigation space-y-4 bg-slate-900 p-5">{nav}<button className="nav-link" onClick={openLearn}><Icon name="book"/>How it works</button><button className="nav-link" disabled={g.busy} onClick={() => { setMobileNav(false); g.signOut(); }}><Icon name="logout"/>Sign out</button></div></Modal>
    {g.secret && <SecretModal secret={g.secret} onClose={() => g.setSecret('')}/>}
  </div>;
}
createRoot(document.getElementById('root')).render(<App/>);
