import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { request, totals } from './api.js';
import './style.css';

function App() {
  const [token, setToken] = useState(''); const [draftToken, setDraftToken] = useState('');
  const [tab, setTab] = useState('Overview'); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const [metrics, setMetrics] = useState(null); const [backends, setBackends] = useState([]); const [keys, setKeys] = useState([]);
  const [config, setConfig] = useState(null); const [editor, setEditor] = useState(''); const [busy, setBusy] = useState(false);
  const [keyName, setKeyName] = useState(''); const [prefixes, setPrefixes] = useState(''); const [days, setDays] = useState(30); const [secret, setSecret] = useState('');
  const [updated, setUpdated] = useState(null);
  const load = async (activeToken = token, all = false) => {
    const [m, b] = await Promise.all([request(activeToken, 'metrics'), request(activeToken, 'backends')]);
    setMetrics(m); setBackends(b); setUpdated(new Date());
    if (all) { const c = await request(activeToken, 'config'); setConfig(c); setEditor(JSON.stringify(c.routes, null, 2)); }
  };
  useEffect(() => { if (!token) return; let alive = true; const timer = setInterval(() => { if (alive) load().catch(e => setError(e.message)); }, 5000); return () => { alive = false; clearInterval(timer); }; }, [token]);
  const action = async (fn) => { setBusy(true); setError(''); setNotice(''); try { await fn(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const signIn = e => { e.preventDefault(); action(async () => { await load(draftToken, true); setToken(draftToken); setDraftToken(''); }); };
  const select = name => { setTab(name); setError(''); setNotice(''); if (name === 'API keys') action(async () => setKeys(await request(token, 'keys'))); };
  const save = () => action(async () => { const routes = JSON.parse(editor); if (!Array.isArray(routes)) throw new Error('Routes must be a JSON array.'); const c = await request(token, 'config', { method: 'PUT', body: JSON.stringify({ revision: config.revision, routes }) }); setConfig(c); setEditor(JSON.stringify(c.routes, null, 2)); setNotice(`Revision ${c.revision} saved. Other instances refresh within 5 seconds.`); await load(); });
  const createKey = e => { e.preventDefault(); action(async () => { const result = await request(token, 'keys', { method: 'POST', body: JSON.stringify({ name: keyName, prefixes: prefixes.split(',').map(p => p.trim()).filter(Boolean), expires_at: new Date(Date.now() + Number(days) * 86400000).toISOString() }) }); setSecret(result.secret); setKeys(await request(token, 'keys')); setKeyName(''); }); };
  const revoke = key => action(async () => { await request(token, `keys/${encodeURIComponent(key.id)}`, { method: 'DELETE' }); setKeys(await request(token, 'keys')); setNotice(`Revoked ${key.name}.`); });
  const sum = totals(metrics?.routes); const healthy = backends.filter(b => b.healthy).length;
  if (!token) return <main className="login"><div className="brand"><span className="mark">G</span> GateForge</div><div className="login-card"><p className="eyebrow">GATEWAY CONTROL ROOM</p><h1>Your services.<br/>One front door.</h1><p>Inspect traffic, manage routes, and control access to your APIs.</p><form onSubmit={signIn}><label htmlFor="token">Administrator token</label><input id="token" type="password" autoComplete="off" value={draftToken} onChange={e => setDraftToken(e.target.value)} required minLength={32}/><button disabled={busy}>{busy ? 'Connecting…' : 'Open control room →'}</button></form>{error && <p role="alert" className="error">{error}</p>}<small>The token stays in this tab’s memory and is cleared on reload.</small></div><p className="login-foot">Secure access · Explicit routing · Observable traffic</p></main>;
  return <div className="shell"><aside><div className="brand"><span className="mark">G</span> GateForge</div><p className="eyebrow">WORKSPACE</p><nav>{['Overview', 'Routes', 'API keys'].map(name => <button key={name} className={name === tab ? 'active' : ''} onClick={() => select(name)}>{name}</button>)}</nav><div className="aside-bottom"><span className="dot"/> Gateway connected<small>One instance · Live metrics</small><button className="quiet" onClick={() => { setToken(''); setSecret(''); setMetrics(null); setError(''); }}>Sign out</button></div></aside><main className="workspace"><header><div><p className="eyebrow">CONTROL ROOM / {tab.toUpperCase()}</p><h1>{tab === 'Overview' ? 'Traffic at a glance' : tab === 'Routes' ? 'Connect your services' : 'Control API access'}</h1><p>{tab === 'Overview' ? 'A live view of the gateway handling your requests.' : tab === 'Routes' ? 'Match a path, choose its backends, and set its policies.' : 'Create scoped credentials and revoke them when access changes.'}</p></div><button className="secondary" disabled={busy} onClick={() => action(() => load(token, tab === 'Routes'))}>Refresh</button></header>{error && <div role="alert" className="error banner">{error}</div>}{notice && <div role="status" className="success banner">{notice}</div>}
    {tab === 'Overview' && <><section className="cards"><Metric title="Total requests" value={sum.requests.toLocaleString()} note="Since this instance started"/><Metric title="Mean latency" value={`${sum.requests ? (sum.seconds * 1000 / sum.requests).toFixed(1) : '0'} ms`} note="Includes gateway processing"/><Metric title="Server errors" value={sum.errors.toLocaleString()} note="Responses with 5xx status"/><Metric title="Cache hit rate" value={`${sum.hits + sum.misses ? Math.round(100 * sum.hits / (sum.hits + sum.misses)) : 0}%`} note="Of eligible cache lookups"/></section><section className="panel"><div className="panel-head"><h2>Service health</h2><span className="pill">{healthy} / {backends.length} available</span></div><div className="table-wrap"><table><thead><tr><th>Route</th><th>Backend</th><th>Status</th><th>Checks</th></tr></thead><tbody>{backends.map(b => <tr key={b.route + b.url}><td><code>{b.route}</code></td><td>{b.url}</td><td><span className={`status ${b.healthy ? 'up' : 'down'}`}>{b.healthy ? 'Available' : 'Unavailable'}</span></td><td>{b.health_checks_enabled ? 'Active' : 'Not configured'}</td></tr>)}</tbody></table></div></section><section className="panel"><div className="panel-head"><h2>Request activity</h2><small>Updated {updated?.toLocaleTimeString()}</small></div><div className="table-wrap"><table><thead><tr><th>Route</th><th>Requests</th><th>Mean latency</th><th>4xx</th><th>5xx</th><th>Cache hits</th></tr></thead><tbody>{metrics?.routes.map(r => <tr key={r.route}><td><code>{r.route}</code></td><td>{r.requests}</td><td>{r.mean_ms.toFixed(1)} ms</td><td>{r.client_errors}</td><td>{r.errors}</td><td>{r.cache_hits}</td></tr>)}</tbody></table>{!metrics?.routes.length && <div className="empty">No traffic yet. Send a request through one of your routes to see activity here.</div>}</div></section><p className="footnote">Metrics are held in memory for this instance. Use the authenticated /metrics endpoint with Prometheus for durable, combined reporting.</p></>}
    {tab === 'Routes' && <section className="panel"><div className="panel-head"><h2>Route configuration</h2><span className="pill">Revision {config?.revision}</span></div><div className="editor-help">The longest matching prefix wins. Use <code>auth: "api_key"</code> or <code>auth: "jwt"</code> to protect a route. Shared caching requires a public route.</div><label className="sr-only" htmlFor="routes">Route configuration JSON</label><textarea id="routes" className="code-editor" spellCheck={false} value={editor} onChange={e => setEditor(e.target.value)}/><div className="panel-actions"><p>Saving validates every route and applies the configuration atomically.</p><button disabled={busy} onClick={save}>{busy ? 'Saving…' : 'Save configuration'}</button></div></section>}
    {tab === 'API keys' && <><section className="panel"><div className="panel-head"><h2>Create an API key</h2><span className="pill">Stored as a hash</span></div><form className="key-form" onSubmit={createKey}><label>Name<input value={keyName} onChange={e => setKeyName(e.target.value)} placeholder="Development client" required maxLength={128}/></label><label>Allowed route prefixes<input value={prefixes} onChange={e => setPrefixes(e.target.value)} placeholder="/users, /orders" required/></label><label>Expires in days<input type="number" value={days} onChange={e => setDays(e.target.value)} min="1" max="90" required/></label><button disabled={busy}>Create key</button></form>{secret && <div className="secret"><strong>Copy this key now. It will not be shown again.</strong><code>{secret}</code><button className="secondary" onClick={() => setSecret('')}>I saved it · Dismiss</button></div>}</section><section className="panel"><div className="panel-head"><h2>Issued keys</h2><small>Most recent 1,000 keys</small></div><div className="table-wrap"><table><thead><tr><th>Name</th><th>Access</th><th>Expires</th><th>Status</th><th/></tr></thead><tbody>{keys.map(k => <tr key={k.id}><td>{k.name}<small className="id">{k.id}</small></td><td>{k.prefixes.join(', ')}</td><td>{new Date(k.expires_at).toLocaleDateString()}</td><td>{k.revoked ? 'Revoked' : new Date(k.expires_at) < new Date() ? 'Expired' : 'Active'}</td><td>{!k.revoked && <button className="danger" disabled={busy} onClick={() => revoke(k)}>Revoke</button>}</td></tr>)}</tbody></table>{!keys.length && <div className="empty">No API keys yet. Create one for a route protected with API-key authentication.</div>}</div></section></>}
  </main></div>;
}
function Metric({ title, value, note }) { return <article className="metric"><p>{title}</p><strong>{value}</strong><small>{note}</small></article>; }
createRoot(document.getElementById('root')).render(<App/>);
