import React, { useEffect, useState, useRef } from 'react';
import { createRoot } from 'react-dom/client';
import { request, totals, actionGate } from './api.js';
import Learn from './Learn.jsx';
import './style.css';

function App() {
  const [learnOpen, setLearnOpen] = useState(() => window.location.hash === '#learn');
  useEffect(() => { const update = () => setLearnOpen(window.location.hash === '#learn'); window.addEventListener('hashchange', update); return () => window.removeEventListener('hashchange', update); }, []);
  const [token, setToken] = useState(''); const [draftToken, setDraftToken] = useState('');
  const [tab, setTab] = useState('Overview'); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const [metrics, setMetrics] = useState(null); const [backends, setBackends] = useState([]); const [keys, setKeys] = useState([]);
  const [config, setConfig] = useState(null); const [editor, setEditor] = useState(''); const [busy, setBusy] = useState(false);
  const [keyName, setKeyName] = useState(''); const [prefixes, setPrefixes] = useState(''); const [days, setDays] = useState(30); const [secret, setSecret] = useState('');
  const [updated, setUpdated] = useState(null);
  const gate = useRef(actionGate()); const session = useRef(new AbortController());
  const creation = useRef(null); const [keysLoading, setKeysLoading] = useState(false);
  const [keysLoaded, setKeysLoaded] = useState(false); const [nextCursor, setNextCursor] = useState('');
  const [cursor, setCursor] = useState(''); const [history, setHistory] = useState([]);
  const api = (activeToken, path, options = {}) => request(activeToken, path, { ...options, signal: session.current.signal });
  const load = async (activeToken = token, all = false, signal = session.current.signal) => {
    const [m, b, c] = await Promise.all([request(activeToken, 'metrics', {signal}), request(activeToken, 'backends', {signal}), all ? request(activeToken, 'config', {signal}) : null]);
    if (signal.aborted) return;
    setMetrics(m); setBackends(b); setUpdated(new Date());
    if (all) { setConfig(c); setEditor(JSON.stringify(c.routes, null, 2)); }
  };
  useEffect(() => { if (!token || learnOpen) return; const controller = new AbortController(); let timer; const poll = async () => { try { await load(token, false, controller.signal); } catch(e) { if (!controller.signal.aborted) setError(e.message); } if (!controller.signal.aborted) timer = setTimeout(poll, 5000); }; timer = setTimeout(poll, 5000); return () => { controller.abort(); clearTimeout(timer); }; }, [token, learnOpen]);
  const action = fn => gate.current(async () => { setBusy(true); setError(''); setNotice(''); try { await fn(); } catch (e) { if(e.name !== 'AbortError') setError(e.message); } finally { setBusy(false); } });
  const loadKeys = async (value = '', past = []) => { setKeysLoading(true); try { const page = await api(token, `keys?limit=50&cursor=${encodeURIComponent(value)}`); setKeys(page.keys); setNextCursor(page.next_cursor || ''); setCursor(value); setHistory(past); setKeysLoaded(true); } finally { setKeysLoading(false); } };
  const signIn = e => { e.preventDefault(); action(async () => { await load(draftToken, true); setToken(draftToken); setDraftToken(''); }); };
  const select = name => { if (name === 'How it works') { window.location.hash = 'learn'; return; } setTab(name); setError(''); setNotice(''); if (name === 'API keys') action(() => loadKeys()); };
  const save = () => action(async () => { const routes = JSON.parse(editor); if (!Array.isArray(routes)) throw new Error('Routes must be a JSON array.'); const c = await api(token, 'config', { method: 'PUT', body: JSON.stringify({ revision: config.revision, routes }) }); setConfig(c); setEditor(JSON.stringify(c.routes, null, 2)); setNotice(`Revision ${c.revision} saved. Other active instances refresh within 5 seconds.`); await load(); });
  const createKey = e => { e.preventDefault(); action(async () => { const form = JSON.stringify([keyName, prefixes, days]); if (creation.current?.form !== form) creation.current = { form, id: crypto.randomUUID(), body: JSON.stringify({ name: keyName, prefixes: prefixes.split(',').map(p => p.trim()).filter(Boolean), expires_at: new Date(Date.now() + Number(days) * 86400000).toISOString() }) }; const pending = creation.current; const result = await api(token, 'keys', { method: 'POST', headers: {'Idempotency-Key': pending.id}, body: pending.body }); setSecret(result.secret); creation.current = null; setKeyName(''); await loadKeys(); }); };
  const revoke = key => action(async () => { await api(token, `keys/${encodeURIComponent(key.id)}`, { method: 'DELETE' }); setNotice(`Revoked ${key.name}.`); await loadKeys(cursor, history); });
  const sum = totals(metrics?.routes); const healthy = backends.filter(b => b.healthy).length;
  if (learnOpen) return <Learn onClose={() => { window.location.hash = ''; }}/>;
  if (!token) return <main className="login"><div className="brand"><span className="mark">G</span> GateForge</div><div className="login-card"><p className="eyebrow">GATEWAY CONTROL ROOM</p><h1>Your services.<br/>One front door.</h1><p>Inspect traffic, manage routes, and control access to your APIs.</p><form onSubmit={signIn}><label htmlFor="token">Administrator token</label><input id="token" type="password" autoComplete="off" value={draftToken} onChange={e => setDraftToken(e.target.value)} required minLength={32}/><button disabled={busy}>{busy ? 'Connecting…' : 'Open control room →'}</button></form>{error && <p role="alert" className="error">{error}</p>}<small>The token stays in this tab’s memory and is cleared on reload.</small><a className="learn-login-link" href="#learn">New to gateways? See how it works →</a></div><p className="login-foot">Secure access · Explicit routing · Observable traffic</p></main>;
  return <div className="shell"><aside><div className="brand"><span className="mark">G</span> GateForge</div><p className="eyebrow">WORKSPACE</p><nav>{['Overview', 'Routes', 'API keys', 'How it works'].map(name => <button key={name} className={name === tab ? 'active' : ''} disabled={busy} onClick={() => select(name)}>{name}</button>)}</nav><div className="aside-bottom"><span className="dot"/> Gateway connected<small>One instance · Live metrics</small><button className="quiet" disabled={busy} onClick={() => { session.current.abort(); session.current = new AbortController(); creation.current = null; setToken(''); setSecret(''); setMetrics(null); setKeys([]); setKeysLoaded(false); setConfig(null); setEditor(''); setError(''); }}>Sign out</button></div></aside><main className="workspace"><header><div><p className="eyebrow">CONTROL ROOM / {tab.toUpperCase()}</p><h1>{tab === 'Overview' ? 'Traffic at a glance' : tab === 'Routes' ? 'Connect your services' : 'Control API access'}</h1><p>{tab === 'Overview' ? 'A live view of the gateway handling your requests.' : tab === 'Routes' ? 'Match a path, choose its backends, and set its policies.' : 'Create scoped credentials and revoke them when access changes.'}</p></div><button className="secondary" disabled={busy} onClick={() => action(() => tab === 'API keys' ? loadKeys(cursor, history) : load(token, tab === 'Routes'))}>Refresh</button></header>{error && <div role="alert" className="error banner">{error}</div>}{notice && <div role="status" className="success banner">{notice}</div>}{busy && <div role="status" className="banner">Working… Please wait.</div>}
    {tab === 'Overview' && <><section className="cards"><Metric title="Total requests" value={sum.requests.toLocaleString()} note="Since this instance started"/><Metric title="Mean latency" value={`${sum.requests ? (sum.seconds * 1000 / sum.requests).toFixed(1) : '0'} ms`} note="Includes gateway processing"/><Metric title="Server errors" value={sum.errors.toLocaleString()} note="Responses with 5xx status"/><Metric title="Cache hit rate" value={`${sum.hits + sum.misses ? Math.round(100 * sum.hits / (sum.hits + sum.misses)) : 0}%`} note="Of eligible cache lookups"/></section><section className="panel"><div className="panel-head"><h2>Service health</h2><span className="pill">{healthy} / {backends.length} available</span></div><div className="table-wrap"><table><thead><tr><th>Route</th><th>Backend</th><th>Status</th><th>Checks</th></tr></thead><tbody>{backends.map(b => <tr key={b.route + b.url}><td><code>{b.route}</code></td><td>{b.url}</td><td><span className={`status ${b.healthy ? 'up' : 'down'}`}>{b.healthy ? 'Available' : 'Unavailable'}</span></td><td>{b.health_checks_enabled ? 'Active' : 'Not configured'}</td></tr>)}</tbody></table>{!backends.length && <div className="empty">No backends configured. Add a route to connect a service.</div>}</div></section><section className="panel"><div className="panel-head"><h2>Request activity</h2><small>Updated {updated?.toLocaleTimeString()}</small></div><div className="table-wrap"><table><thead><tr><th>Route</th><th>Requests</th><th>Mean latency</th><th>4xx</th><th>5xx</th><th>Cache hits</th></tr></thead><tbody>{metrics?.routes.map(r => <tr key={r.route}><td><code>{r.route}</code></td><td>{r.requests}</td><td>{r.mean_ms.toFixed(1)} ms</td><td>{r.client_errors}</td><td>{r.errors}</td><td>{r.cache_hits}</td></tr>)}</tbody></table>{!metrics?.routes.length && <div className="empty">No traffic yet. Send a request through one of your routes to see activity here.</div>}</div></section><p className="footnote">Metrics are held in memory for this instance. Use the authenticated /metrics endpoint with Prometheus for durable, combined reporting.</p></>}
    {tab === 'Routes' && <section className="panel"><div className="panel-head"><h2>Route configuration</h2><span className="pill">Revision {config?.revision}</span></div><div className="editor-help">The longest matching prefix wins. Use <code>auth: "api_key"</code> or <code>auth: "jwt"</code> to protect a route. Shared caching requires a public route.</div><label className="sr-only" htmlFor="routes">Route configuration JSON</label><textarea id="routes" className="code-editor" spellCheck={false} value={editor} onChange={e => setEditor(e.target.value)}/><div className="panel-actions"><p>Saving validates every route and applies the configuration atomically.</p><button disabled={busy} onClick={save}>{busy ? 'Saving…' : 'Save configuration'}</button></div></section>}
    {tab === 'API keys' && <><section className="panel"><div className="panel-head"><h2>Create an API key</h2><span className="pill">Stored as a hash</span></div><form className="key-form" onSubmit={createKey}><label>Name<input value={keyName} onChange={e => setKeyName(e.target.value)} placeholder="Development client" required maxLength={128}/></label><label>Allowed route prefixes<input value={prefixes} onChange={e => setPrefixes(e.target.value)} placeholder="/users, /orders" required/></label><label>Expires in days<input type="number" value={days} onChange={e => setDays(e.target.value)} min="1" max="90" required/></label><button disabled={busy}>Create key</button></form>{secret && <div className="secret"><strong>Copy this key now. It will not be shown again.</strong><code>{secret}</code><button className="secondary" onClick={() => setSecret('')}>I saved it · Dismiss</button></div>}</section><section className="panel"><div className="panel-head"><h2>Issued keys</h2><small>{keysLoading ? 'Loading keys…' : `Page ${history.length + 1} · Up to 50 keys`}</small></div><div className="table-wrap"><table><thead><tr><th>Name</th><th>Access</th><th>Expires</th><th>Status</th><th/></tr></thead><tbody>{keys.map(k => <tr key={k.id}><td>{k.name}<small className="id">{k.id}</small></td><td>{k.prefixes.join(', ')}</td><td>{new Date(k.expires_at).toLocaleDateString()}</td><td>{k.revoked ? 'Revoked' : new Date(k.expires_at) < new Date() ? 'Expired' : 'Active'}</td><td>{!k.revoked && <button className="danger" disabled={busy} onClick={() => revoke(k)}>Revoke</button>}</td></tr>)}</tbody></table>{keysLoaded && !keysLoading && !keys.length && <div className="empty">No keys on this page. Create an API key or return to the first page.</div>}{!keysLoaded && !keysLoading && <div className="empty">Keys could not be loaded. Use Refresh to try again.</div>}</div><div className="panel-actions"><button className="secondary" disabled={busy || !history.length} onClick={() => action(() => loadKeys(history.at(-1), history.slice(0, -1)))}>Previous</button><button className="secondary" disabled={busy || !nextCursor} onClick={() => action(() => loadKeys(nextCursor, [...history, cursor]))}>Next</button></div></section></>}
  </main></div>;
}
function Metric({ title, value, note }) { return <article className="metric"><p>{title}</p><strong>{value}</strong><small>{note}</small></article>; }
createRoot(document.getElementById('root')).render(<App/>);
