import React, { useState } from 'react';
import PolicyEditor from './PolicyEditor.jsx';
import { totals } from './api.js';
import { Badge, Button, Empty, Icon, Modal, Notice, Panel } from './components.jsx';
import { filterKeys, keyStatus, routeAuth, routeTargets } from './dashboard-model.js';

function Metric({ icon, label, value, detail, accent = false }) {
  return <article className={`panel p-5 sm:p-6 ${accent ? 'metric-accent' : ''}`}><div className="flex items-center justify-between gap-2"><p className="text-xs font-medium text-slate-500">{label}</p><span className={`rounded-lg p-2 ${accent ? 'bg-teal-100 text-teal-700' : 'bg-slate-50 text-slate-400'}`}><Icon name={icon} className="size-4"/></span></div><p className="mt-4 text-[30px] font-semibold leading-none tracking-tight text-slate-900 tabular-nums">{value}</p><p className="mt-3 text-[11px] leading-5 text-slate-500">{detail}</p></article>;
}
export function Overview({ gateway: g }) {
  const sum = totals(g.metrics?.routes); const rows = g.metrics?.routes || [];
  const healthy = g.backends.filter(b => b.health_checks_enabled && b.healthy).length;
  return <div className="space-y-6"><div className="grid grid-cols-2 gap-3 xl:grid-cols-4 xl:gap-5">
    <Metric icon="activity" label="Total requests" value={sum.requests.toLocaleString()} detail={g.metrics?.scope === 'shared' ? 'Persisted across gateway instances' : 'Since this instance started'} accent/>
    <Metric icon="clock" label="Average latency" value={`${sum.requests ? (sum.seconds * 1000 / sum.requests).toFixed(1) : '0'} ms`} detail="Including gateway processing"/>
    <Metric icon="alert" label="Server errors" value={sum.errors.toLocaleString()} detail="Responses with a 5xx status"/>
    <Metric icon="cache" label="Cache hit rate" value={`${sum.hits + sum.misses ? Math.round(100 * sum.hits / (sum.hits + sum.misses)) : 0}%`} detail="Of eligible cache lookups"/>
  </div><div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1.7fr)_minmax(270px,1fr)]"><Panel title="Service health" subtitle="Availability across your configured backends" action={<Badge tone={healthy === g.backends.length && healthy ? 'success' : 'neutral'} dot>{healthy} / {g.backends.length} healthy</Badge>}>
    {g.backends.length ? <div className="table-scroll"><table className="data-table"><thead><tr><th>Route / backend</th><th>Status</th><th>Health checks</th></tr></thead><tbody>{g.backends.map(b => <tr key={b.route + b.name}><td><div className="flex items-center gap-3"><span className="hidden rounded-lg border border-slate-200 p-2 text-slate-400 sm:block"><Icon name="server" className="size-4"/></span><div><code className="text-xs font-semibold text-slate-800">{b.route}</code><p className="mt-1 font-mono text-[10px] text-slate-500">{b.name}</p></div></div></td><td><Badge tone={!b.health_checks_enabled ? 'neutral' : b.healthy ? 'success' : 'danger'} dot>{!b.health_checks_enabled ? 'Unmonitored' : b.healthy ? 'Healthy' : 'Unavailable'}</Badge></td><td className="text-xs text-slate-500">{b.health_checks_enabled ? 'Enabled' : 'Not configured'}</td></tr>)}</tbody></table></div> : <Empty icon="server" title="No backends yet" action={<Button variant="secondary" onClick={() => g.select('Routes')}>Configure routes</Button>}>Add a route to connect your first service.</Empty>}
  </Panel><Panel title="Traffic distribution" subtitle={g.metrics?.scope === 'shared' ? 'Requests by route · shared history' : 'Requests by route · current instance'}>{sum.requests ? <div className="space-y-5 p-6">{rows.slice().sort((a,b) => b.requests-a.requests).slice(0,6).map(r => <div key={r.route}><div className="mb-2 flex items-center justify-between gap-3 text-xs"><code className="truncate font-medium text-slate-700">{r.route}</code><span className="shrink-0 text-slate-500 tabular-nums">{r.requests.toLocaleString()} <span className="ml-2 text-slate-400">{Math.round(r.requests / sum.requests * 100)}%</span></span></div><progress className="traffic-bar" max={sum.requests} value={r.requests} aria-label={`${r.route} share of requests`}/></div>)}{rows.length>6 && <p className="text-xs text-slate-400">Showing the six busiest routes.</p>}</div> : <Empty title="Waiting for traffic">Send a request through a configured route to see its share here.</Empty>}</Panel></div>
  <Panel title="Request activity" subtitle={g.metrics?.scope === 'shared' ? 'Durable cumulative counters across gateway instances' : 'Cumulative counters for the current gateway instance'} action={<span className="flex items-center gap-1.5 text-[11px] text-slate-400"><Icon name="refresh" className="size-3.5"/>Refreshes every 5s</span>}>
    {rows.length ? <div className="table-scroll"><table className="data-table"><thead><tr><th>Route</th><th className="text-right">Requests</th><th className="text-right">Avg. latency</th><th className="text-right">4xx errors</th><th className="text-right">5xx errors</th><th className="text-right">Cache hits</th></tr></thead><tbody>{rows.map(r => <tr key={r.route}><td><code className="font-medium text-slate-800">{r.route}</code></td><td className="text-right tabular-nums">{r.requests.toLocaleString()}</td><td className="text-right tabular-nums">{r.mean_ms.toFixed(1)} ms</td><td className="text-right tabular-nums">{r.client_errors}</td><td className={`text-right tabular-nums ${r.errors ? 'font-semibold text-rose-600' : ''}`}>{r.errors}</td><td className="text-right tabular-nums">{r.cache_hits}</td></tr>)}</tbody></table></div> : <Empty title="No requests recorded">Your route activity will appear after the first request.</Empty>}
  </Panel><p className="flex items-start gap-2 px-1 text-xs leading-6 text-slate-400"><Icon name="activity" className="mt-1 size-4"/>{g.metrics?.scope === 'shared' ? 'Shared counters are persisted to PostgreSQL. The newest unflushed requests can be lost on a crash; these are operational metrics, not billing records.' : 'Metrics reset when this instance restarts. Configure PostgreSQL for shared reporting.'}</p></div>;
}

export function Routes({ gateway: g }) {
  const [editing, setEditing] = useState(false); const [editor, setEditor] = useState(''); const [revision, setRevision] = useState(null);
  const routes = g.config?.routes || [];
  function edit() { setEditor(JSON.stringify(routes, null, 2)); setRevision(g.config.revision); g.setError(''); setEditing(true); }
  return <><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><Badge>{routes.length} routes</Badge><Badge tone="accent">Revision {g.config?.revision}</Badge></div><Button icon="code" onClick={edit} disabled={g.busy || !g.config}>Edit policies</Button></div>
    <div className="grid gap-5 xl:grid-cols-2">{routes.map(route => <section className="panel overflow-hidden" key={route.prefix}><div className="flex items-center justify-between gap-3 border-b border-slate-100 px-6 py-5"><div className="flex items-center gap-3"><span className="rounded-xl bg-teal-50 p-2.5 text-teal-700"><Icon name="routes"/></span><div><code className="text-lg font-semibold tracking-tight">{route.prefix}</code><p className="mt-1 text-[11px] text-slate-500">Path-prefix routing</p></div></div><Badge tone={route.auth && route.auth !== 'public' ? 'accent' : 'neutral'}>{routeAuth(route)}</Badge></div><div className="space-y-5 p-6"><div><p className="mb-2 text-[10px] font-semibold uppercase tracking-widest text-slate-400">Backend pool</p>{routeTargets(route).map(url => <div key={url} className="mt-2 flex items-center gap-2 rounded-lg bg-slate-50 px-3 py-2.5 text-slate-500"><Icon name="server" className="size-4"/><code className="min-w-0 break-all text-xs text-slate-700">{url}</code></div>)}</div><div className="grid grid-cols-2 gap-x-5 gap-y-4 border-t border-slate-100 pt-5"><RouteDetail label="Rate limit" value={route.rate_limit ? `${route.rate_limit.requests} / ${route.rate_limit.window_seconds}s` : 'Not configured'}/><RouteDetail label="Request timeout" value={`${(route.timeout_ms || 10000) / 1000}s`}/><RouteDetail label="Response cache" value={route.cache ? `Up to ${route.cache.ttl_seconds}s` : 'Disabled'}/><RouteDetail label="Safe retries" value={route.retries || 'None'}/></div></div></section>)}</div>
    {!routes.length && <div className="panel"><Empty icon="routes" title="No routes configured">Configure a path prefix and backend to start forwarding traffic.</Empty></div>}
    <div className="mt-6 flex items-start gap-3 rounded-xl border border-slate-200/80 bg-white/50 p-5 text-xs leading-6 text-slate-500"><Icon name="shield" className="mt-0.5 size-4 text-teal-700"/><span>The longest matching path prefix wins. Shared response caching is limited to public routes. Changes are validated before being saved. Backend destinations are managed on the server.</span></div>
    <Modal open={editing} onClose={() => setEditing(false)} busy={g.busy} wide title="Preview route policies" description={`Editing revision ${revision}. Preview historical samples before applying.`}>{editing && <PolicyEditor gateway={g} initial={editor} revision={revision} onClose={() => setEditing(false)}/>}</Modal>
  </>;
}
function RouteDetail({ label, value }) { return <div><p className="text-[11px] text-slate-400">{label}</p><p className="mt-1.5 text-sm font-medium text-slate-700">{value}</p></div>; }

export function Keys({ gateway: g }) {
  const [search, setSearch] = useState(''); const [hideRevoked, setHideRevoked] = useState(true); const [creating, setCreating] = useState(false); const [revoking, setRevoking] = useState(null);
  const [tenant, setTenant] = useState(''); const [name, setName] = useState(''); const [prefixes, setPrefixes] = useState([]); const [days, setDays] = useState(30);
  const eligible = (g.config?.routes || []).filter(r => r.auth === 'api_key' || r.auth === 'either');
  const visible = filterKeys(g.keys, search, hideRevoked);
  return <><Panel title="API keys" subtitle="Scoped access for your clients and services" action={<Button icon="plus" disabled={g.busy} onClick={() => { g.setError(''); setCreating(true); }}>Create API key</Button>}>
    <div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-100 px-5 py-4 sm:px-6"><div className="relative w-full sm:max-w-xs"><Icon name="search" className="pointer-events-none absolute top-3 left-3 size-4 text-slate-400"/><input aria-label="Search keys on this page" className="field pl-10" placeholder="Search this page…" value={search} onChange={e => setSearch(e.target.value)}/></div><label className="flex cursor-pointer items-center gap-2 text-xs text-slate-500"><input type="checkbox" className="size-4 accent-teal-700" checked={hideRevoked} onChange={e => setHideRevoked(e.target.checked)}/>Hide revoked keys</label></div>
    {g.keysLoading ? <div role="status" className="space-y-5 p-6"><span className="sr-only">Loading API keys</span>{[1,2,3].map(n => <div key={n} className="h-12 animate-pulse rounded-lg bg-slate-100"/>)}</div> : visible.length ? <div className="table-scroll"><table className="data-table"><thead><tr><th>Name</th><th>Allowed routes</th><th>Expires</th><th>Status</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{visible.map(key => { const status = keyStatus(key); return <tr key={key.id}><td><div className="flex items-center gap-3"><span className="rounded-lg bg-slate-50 p-2 text-slate-400"><Icon name="key" className="size-4"/></span><div className="max-w-64"><p className="break-words font-medium text-slate-800">{key.name}</p><p className="mt-1 font-mono text-[10px] text-slate-400">ID · {key.id.slice(0,12)}…</p></div></div></td><td><div className="flex flex-wrap gap-1.5">{key.prefixes.map(prefix => <code key={prefix} className="rounded bg-slate-100 px-2 py-1 text-[10px] text-slate-600">{prefix}</code>)}</div></td><td className="whitespace-nowrap text-xs">{new Date(key.expires_at).toLocaleDateString(undefined, {month:'short',day:'numeric',year:'numeric'})}</td><td><Badge tone={status === 'Active' ? 'success' : status === 'Expired' ? 'warning' : 'neutral'} dot>{status}</Badge></td><td>{!key.revoked && <button className="rounded-lg px-3 py-2 text-xs font-medium text-rose-600 hover:bg-rose-50 disabled:opacity-40" aria-label={`Revoke ${key.name}`} disabled={g.busy} onClick={() => { g.setError(''); setRevoking(key); }}>Revoke</button>}</td></tr>; })}</tbody></table></div> : <Empty icon="key" title={!g.keysLoaded ? 'Could not load keys' : g.keys.length ? 'No matching keys' : 'No API keys yet'} action={!g.keysLoaded ? <Button variant="secondary" onClick={g.refresh}>Try again</Button> : undefined}>{!g.keysLoaded ? 'Refresh to try loading your keys again.' : g.keys.length ? 'Try another search or include revoked keys. Filters apply to this page.' : 'Create a scoped key to give a client access to protected routes.'}</Empty>}
    <div className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 px-5 py-4 sm:px-6"><p className="text-xs text-slate-400">Page {g.history.length + 1} · {visible.length} shown · Up to 50 per page</p><div className="flex gap-2"><Button variant="secondary" disabled={g.busy || !g.history.length} onClick={g.previousPage}>Previous</Button><Button variant="secondary" disabled={g.busy || !g.nextCursor} onClick={g.nextPage}>Next</Button></div></div>
  </Panel><p className="mt-5 flex items-start gap-2 px-1 text-xs leading-6 text-slate-500"><Icon name="shield" className="mt-1 size-4 text-teal-700"/>Keys are stored as hashes. Send a key in the X-API-Key header; it does not grant administrator access.</p>
  <Modal open={creating} onClose={() => setCreating(false)} busy={g.busy} title="Create an API key" description="Give a client access to only the routes it needs."><form onSubmit={async e => { e.preventDefault(); if (await g.createKey({name, prefixes, days, tenant_id:tenant})) { setCreating(false); setName(''); setPrefixes([]); } }}><div className="space-y-5 p-6"><Notice>{g.error}</Notice><label className="field-label">Tenant ID<input className="field mt-2" value={tenant} onChange={e=>setTenant(e.target.value)} maxLength={128} placeholder="Same customer → same tenant ID"/><span className="text-xs font-normal text-slate-500">Keys with the same tenant share concurrency limits. Blank gives this key its own allowance.</span></label><label className="field-label">Key name<input className="field mt-2" placeholder="e.g. Development client" value={name} onChange={e => setName(e.target.value)} required maxLength={128} disabled={g.busy}/></label><fieldset disabled={g.busy}><legend className="field-label mb-2">Allowed routes</legend>{eligible.length ? <div className="space-y-2">{eligible.map(route => <label key={route.prefix} className="flex cursor-pointer items-center justify-between gap-3 rounded-lg border border-slate-200 p-3"><span className="flex items-center gap-3"><input type="checkbox" className="size-4 accent-teal-700" checked={prefixes.includes(route.prefix)} onChange={e => setPrefixes(p => e.target.checked ? [...p,route.prefix] : p.filter(x => x!==route.prefix))}/><code className="text-sm text-slate-700">{route.prefix}</code></span><Badge>{routeAuth(route)}</Badge></label>)}</div> : <p className="rounded-lg bg-amber-50 p-3 text-xs leading-6 text-amber-800">Configure a route with API-key authentication before creating a key.</p>}</fieldset><label className="field-label">Expires in<select className="field mt-2" value={days} onChange={e => setDays(Number(e.target.value))} disabled={g.busy}>{[1,7,30,90].map(day => <option key={day} value={day}>{day} {day === 1 ? 'day' : 'days'}</option>)}</select></label><p className="text-xs leading-6 text-slate-400">The secret is shown once after creation. You can revoke access at any time.</p></div><div className="modal-actions"><Button variant="secondary" disabled={g.busy} onClick={() => setCreating(false)}>Cancel</Button><Button type="submit" icon="key" busy={g.busy} disabled={!prefixes.length}>Create key</Button></div></form></Modal>
  <Modal open={!!revoking} onClose={() => setRevoking(null)} busy={g.busy} title="Revoke API key?" description="Clients using this key will immediately lose access."><div className="space-y-4 p-6"><Notice>{g.error}</Notice><div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="break-words text-sm font-semibold">{revoking?.name}</p><p className="mt-1 font-mono text-xs text-slate-500">{revoking?.prefixes.join(', ')}</p></div><p className="text-sm leading-6 text-slate-500">This cannot be undone. Create a replacement key first if a client still needs access.</p></div><div className="modal-actions"><Button variant="secondary" disabled={g.busy} onClick={() => setRevoking(null)}>Keep key</Button><Button variant="danger" busy={g.busy} onClick={async () => { if (await g.revoke(revoking)) setRevoking(null); }}>Revoke key</Button></div></Modal>
  </>;
}

export function SecretModal({ secret, onClose }) {
  const [revealed, setRevealed] = useState(false); const [copied, setCopied] = useState(false); const [copyError, setCopyError] = useState('');
  async function copy() { try { await navigator.clipboard.writeText(secret); setCopied(true); } catch { setCopyError('Clipboard access is unavailable. Reveal the key and copy it manually.'); } }
  return <Modal open={!!secret} title="Your API key is ready" description="Save it somewhere private. You cannot retrieve the secret again." onClose={onClose}><div className="space-y-4 p-6"><Notice type="success">Key created successfully. Its route permissions are active.</Notice><label className="field-label">API key<input className="field mt-2 font-mono text-xs" type={revealed ? 'text' : 'password'} value={secret} readOnly autoComplete="off" spellCheck={false}/></label><div className="flex gap-2"><Button variant="secondary" onClick={() => setRevealed(v => !v)}>{revealed ? 'Hide key' : 'Reveal key'}</Button><Button variant="secondary" icon={copied ? 'check' : 'copy'} onClick={copy}>{copied ? 'Copied' : 'Copy key'}</Button></div><Notice>{copyError}</Notice><p className="text-xs text-slate-500">Use the <code>X-API-Key</code> request header. Do not put this key in a URL or source control.</p></div><div className="modal-actions"><Button onClick={onClose}>I saved my key</Button></div></Modal>;
}
